<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product as ModelsProduct;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        ModelsProduct::insert([
            [
                'id' => '1',
                'productName' => 'carrot',
                'productNameGuj' => 'ગાજર',
                'productNameHin' => 'गाजर',
                'productDescription' => 'Carrot is a crunchy, sweet, and nutritious root vegetable rich in vitamins and antioxidants.',
                'productDescriptionGuj' => 'ગાજર એક કરકરો, મીઠો અને પોષક મૂળભૂત શાકભાજી છે, જે વિટામિન અને એન્ટીઓક્સિડન્ટથી ભરપૂર છે.',
                'productDescriptionHin' => 'गाजर एक कुरकुरी, मीठी और पोषक जड़ वाली सब्जी है, जो विटामिन और एंटीऑक्सीडेंट से भरपूर होती है।',
                'productPrice' => '100',
                'categoryId' => '1',
                'userId' => '1',
                'stock' => '20',
                'image' => 'carrot.jpg',
                'season' => 'winter',
                'status' => 'active',
            ],
            [
                'id' => '2',
                'productName' => 'mango',
                'productNameGuj' => 'કેરી',
                'productNameHin' => 'आम',
                'productDescription' => 'Mango is a juicy and tropical fruit known for its sweet taste and rich nutritional value.',
                'productDescriptionGuj' => 'કેરી એક રસદાર અને ઉષ્ણકટિબંધિયું ફળ છે, જે તેની મીઠાશ અને પોષકતાથી જાણીતું છે.',
                'productDescriptionHin' => 'आम एक रसीला और उष्णकटिबंधीय फल है, जो अपनी मिठास और पोषण मूल्य के लिए जाना जाता है।',
                'productPrice' => '150',
                'categoryId' => '2',
                'userId' => '1',
                'stock' => '30',
                'image' => 'mango.jpg',
                'season' => 'summer',
                'status' => 'active',
            ],
            [
                'id' => '3',
                'productName' => 'spinach',
                'productNameGuj' => 'પાલક',
                'productNameHin' => 'पालक',
                'productDescription' => 'Spinach is a leafy green vegetable rich in iron, vitamins, and essential minerals.',
                'productDescriptionGuj' => 'પાલક એક લીલું શાક છે, જે લોહી, વિટામિન અને જરૂરી ખનિજો ધરાવે છે.',
                'productDescriptionHin' => 'पालक एक पत्तेदार हरी सब्जी है, जो आयरन, विटामिन और आवश्यक खनिजों से भरपूर होती है।',
                'productPrice' => '80',
                'categoryId' => '1',
                'userId' => '1',
                'stock' => '25',
                'image' => 'spinach.jpg',
                'season' => 'monsoon',
                'status' => 'active',
            ],
            [
                'id' => '4',
                'productName' => 'apple',
                'productNameGuj' => 'સફરજન',
                'productNameHin' => 'सेब',
                'productDescription' => 'Apple is a crisp, sweet fruit packed with fiber, vitamins, and antioxidants.',
                'productDescriptionGuj' => 'સફરજન એક કઠણ, મીઠું ફળ છે, જેમાં ફાઈબર, વિટામિન અને એન્ટીઓક્સિડન્ટ ભરપૂર છે.',
                'productDescriptionHin' => 'सेब एक कुरकुरा, मीठा फल है, जो फाइबर, विटामिन और एंटीऑक्सीडेंट से भरपूर होता है।',
                'productPrice' => '200',
                'categoryId' => '2',
                'userId' => '1',
                'stock' => '15',
                'image' => 'apple.jpg',
                'season' => 'winter',
                'status' => 'active',
            ],
            [
                'id' => '5',
                'productName' => 'cucumber',
                'productNameGuj' => 'કાકડી',
                'productNameHin' => 'खीरा',
                'productDescription' => 'Cucumber is a refreshing and hydrating vegetable, perfect for summer.',
                'productDescriptionGuj' => 'કાકડી એક તાજગીભર્યું અને હાઈડ્રેટિંગ શાક છે, જે ગરમીઓ માટે ઉત્તમ છે.',
                'productDescriptionHin' => 'खीरा एक ताज़गी देने वाली और हाइड्रेटिंग सब्जी है, जो गर्मियों के लिए आदर्श है।',
                'productPrice' => '60',
                'categoryId' => '1',
                'userId' => '1',
                'stock' => '40',
                'image' => 'cucumber.jpg',
                'season' => 'summer',
                'status' => 'active',
            ],
            [
                'id' => '6',
                'productName' => 'potato',
                'productNameGuj' => 'બટેટા',
                'productNameHin' => 'आलू',
                'productDescription' => 'Potato is a versatile and starchy vegetable used in various cuisines worldwide.',
                'productDescriptionGuj' => 'બટેટા એક બહુમુખી અને સ્ટાર્ચી શાકભાજી છે, જે વિશ્વભરમાં વિવિધ વાનગીઓમાં વપરાય છે.',
                'productDescriptionHin' => 'आलू एक बहुपयोगी और स्टार्च युक्त सब्जी है, जो विभिन्न व्यंजनों में प्रयोग होती है।',
                'productPrice' => '50',
                'categoryId' => '1',
                'userId' => '1',
                'stock' => '35',
                'image' => 'potato.jpg',
                'season' => 'all',
                'status' => 'active',
            ],
            [
                'id' => '7',
                'productName' => 'onion',
                'productNameGuj' => 'ડુંગળી',
                'productNameHin' => 'प्याज',
                'productDescription' => 'Onion is a pungent vegetable commonly used to enhance the flavor of dishes.',
                'productDescriptionGuj' => 'ડુંગળી એક તીવ્ર શાક છે, જે વાનગીઓની સ્વાદિષ્ટતા વધારવા માટે વપરાય છે.',
                'productDescriptionHin' => 'प्याज एक तीव्र सब्जी है, जो व्यंजनों के स्वाद को बढ़ाने में मदद करती है।',
                'productPrice' => '70',
                'categoryId' => '1',
                'userId' => '1',
                'stock' => '45',
                'image' => 'onion.jpg',
                'season' => 'all',
                'status' => 'active',
            ]
        ]);
    }
}
