<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Product as ModelsProduct;
class ProductSeeder extends Seeder
{
    public function run(): void
    {
        ModelsProduct::insert([
            [
                'id' => '1',
                'productName' => 'Ashirwad Atta',
                'productNameGuj' => 'આશીર્વાદ આટા',
                'productNameHin' => 'आशीर्वाद आटा',
                'productDescription' => 'Aashirvaad Atta is a premium-quality whole wheat flour known for its freshness, softness, and rich taste, made using the traditional chakki-grinding process.',
                'productDescriptionGuj' => 'આશીર્વાદ આટા એક પ્રીમિયમ ગુણવત્તાવાળો ઘઉંનો લોટ છે, જે તેની તાજગી, નરમાઈ અને સમૃદ્ધ સ્વાદ માટે જાણીતો છે, અને તેને પરંપરાગત ચક્કી પીસવાની પ્રક્રિયા દ્વારા બનાવવામાં આવે છે.',
                'productDescriptionHin' => 'आशीर्वाद आटा एक प्रीमियम गुणवत्ता वाला गेहूं का आटा है, जो ताजगी, नरमपन और समृद्ध स्वाद के लिए जाना जाता है, और इसे पारंपरिक चक्की पिसाई प्रक्रिया से बनाया जाता है।',
                'productPrice' => '294',
                'categoryId' => '5',
                'userId' => '1',
                'stock' => '500',
                'image' => 'productImages/AashirvaadAtta.jpeg',
                'season' => 'All',
                'brandId' => '7',
                'isOnHome' => 'yes',
                'status' => 'active',
            ],
            [
                'id' => '2',
                'productName' => 'Daawat Rozana Basmati Rice, 5KG ',
                'productNameGuj' => 'દાવત રોજાના બાસમતી ભાત',
                'productNameHin' => 'दावत रोज़ाना बासमती चावल',
                'productDescription' => 'Daawat Rozana Basmati Rice is a premium-quality everyday rice known for its rich aroma, long grains, and delicious taste.',
                'productDescriptionGuj' => 'दावत रोज़ाना बासमती चावल एक प्रीमियम गुणवत्ता वाला रोज़ाना उपयोग का चावल है, जो अपनी सुगंध, लंबे दानों और स्वाद के लिए जाना जाता है।',
                'productDescriptionHin' => 'દાવત રોજાના બાસમતી ભાત એક પ્રીમિયમ ગુણવત્તાવાળો રોજબરોજ વપરાતો ભાત છે, જે તેની સુગંધ, લાંબા દાણા અને સ્વાદ માટે જાણીતો છે.',
                'productPrice' => '560',
                'categoryId' => '8',
                'userId' => '1',
                'stock' => '600',
                'image' => 'productImages/DaawatRozanaBasmatiRice.jpeg',
                'season' => 'All',
                'brandId' => '16',
                'isOnHome' => 'yes',
                'status' => 'active',
            ],
            [
                'id' => '3',
                'productName' => 'FORTUNE Xpert Pro Immunity Blended Oil Pouch  (1 L)',
                'productNameGuj' => 'ફોર્ચ્યુન એક્સપર્ટ પ્રો ઇમ્યુનિટી બ્લેન્ડેડ તેલ પાઉચ (1 લિટર)',
                'productNameHin' => 'फॉर्च्यून एक्सपर्ट प्रो इम्युनिटी ब्लेंडेड ऑयल पाउच (1 लीटर)',
                'productDescription' => 'FORTUNE Xpert Pro Immunity Blended Oil supports better immunity with a unique blend of healthy oils.',
                'productDescriptionGuj' => 'ફોર્ચ્યુન એક્સપર્ટ પ્રો ઇમ્યુનિટી બ્લેન્ડેડ તેલ આરોગ્યપ્રદ તેલના અનન્ય મિશ્રણથી રોગપ્રતિકારક શક્તિ વધારવામાં મદદ કરે છે.',
                'productDescriptionHin' => 'फॉर्च्यून एक्सपर्ट प्रो इम्युनिटी ब्लेंडेड ऑयल स्वास्थ्यवर्धक तेलों के विशेष मिश्रण से इम्युनिटी को बेहतर बनाता है।',
                'productPrice' => '143',
                'categoryId' => '13',
                'userId' => '1',
                'stock' => '500',
                'image' => 'productImages\FORTUNEXpertProImmunityBlendedOil.jpeg',
                'season' => 'All',
                'brandId' => '5',
                'isOnHome' => 'yes',
                'status' => 'active',
            ],
            [
                'id' => '4',
                'productName' => 'Aashirvaad Svasti Pure Cow Ghee, 1L',
                'productNameGuj' => 'આશીર્વાદ સ્વસ્તિ શુદ્ધ ગાય ઘી',
                'productNameHin' => 'आशीर्वाद स्वस्ति शुद्ध गाय घी',
                'productDescription' => 'Aashirvaad Svasti Pure Cow Ghee is made from high-quality cows milk, offering rich aroma, authentic taste, and purity.',
                'productDescriptionGuj' => 'આશીર્વાદ સ્વસ્તિ શુદ્ધ ગાય ઘી ઉચ્ચ ગુણવત્તાવાળા ગાયના દૂધમાંથી બનેલું છે, જે સમૃદ્ધ સુગંધ, ખરા સ્વાદ અને શુદ્ધતા પ્રદાન કરે છે.',
                'productDescriptionHin' => 'आशीर्वाद स्वस्ति शुद्ध गाय घी उच्च गुणवत्ता वाले गाय के दूध से बना है, जो समृद्ध सुगंध, प्रामाणिक स्वाद और शुद्धता प्रदान करता है।',
                'productPrice' => '528',
                'categoryId' => '14',
                'userId' => '1',
                'stock' => '550',
                'image' => 'productImages/AashirvaadSvastiPureCowGhee.jpeg',
                'season' => 'All',
                'brandId' => '7',
                'isOnHome' => 'yes',
                'status' => 'active',
            ],
            [
                'id' => '5',
                'productName' => 'India Gate Classic Basmati Rice, 5KG',
                'productNameGuj' => 'ઇન્ડિયા ગેટ ક્લાસિક બાસમતી ભાત',
                'productNameHin' => 'इंडिया गेट क्लासिक बासमती चावल',
                'productDescription' => 'India Gate Classic Basmati Rice is known for its delicate aroma, extra-long grains, and superior taste.',
                'productDescriptionGuj' => 'ઇન્ડિયા ગેટ ક્લાસિક બાસમતી ભાત તેની નાજુક સુગંધ, વધારાના લાંબા દાણા અને ઉત્તમ સ્વાદ માટે જાણીતો છે.',
                'productDescriptionHin' => 'इंडिया गेट क्लासिक बासमती चावल अपनी नाजुक सुगंध, अतिरिक्त लंबे दानों और बेहतरीन स्वाद के लिए जाना जाता है।',
                'productPrice' => '1255',
                'categoryId' => '8',
                'userId' => '1',
                'stock' => '600',
                'image' => 'productImages/IndiaGateClassicBasmatiRice.jpeg',
                'season' => 'All',
                'brandId' => '15',
                'isOnHome' => 'yes',
                'status' => 'active',
            ],
            [
                'id' => '6',
                'productName' => 'Patanjali Cow Ghee, 1L',
                'productNameGuj' => 'પતંજલી ગાય ઘી',
                'productNameHin' => 'पतंजलि गाय घी',
                'productDescription' => 'Patanjali Cow Ghee is made from pure cow milk, offering natural aroma and rich taste.',
                'productDescriptionGuj' => 'પતંજલી ગાય ઘી શુદ્ધ ગાયના દૂધમાંથી બનેલું છે, જે કુદરતી સુગંધ અને સમૃદ્ધ સ્વાદ આપે છે.',
                'productDescriptionHin' => 'पतंजलि गाय घी शुद्ध गाय के दूध से बना है, जो प्राकृतिक सुगंध और समृद्ध स्वाद प्रदान करता है।',
                'productPrice' => '540',
                'categoryId' => '14',
                'userId' => '1',
                'stock' => '500',
                'image' => 'productImages/PatanjaliCowGhee.jpeg',
                'season' => 'All',
                'brandId' => '14',
                'isOnHome' => 'yes',
                'status' => 'active'
            ],

            [
                'id' => '7',
                'productName' => 'FORTUNE Mustard Oil',
                'productNameGuj' => 'ફોર્ચ્યુન સરસવ તેલ',
                'productNameHin' => 'फॉर्च्यून सरसों तेल',
                'productDescription' => 'FORTUNE Mustard Oil is known for its strong aroma and natural purity, perfect for traditional Indian cooking.',
                'productDescriptionGuj' => 'ફોર્ચ્યુન સરસવ તેલ તેની તીવ્ર સુગંધ અને કુદરતી શુદ્ધતા માટે જાણીતું છે, જે પરંપરાગત ભારતીય રસોઈ માટે આદર્શ છે.',
                'productDescriptionHin' => 'फॉर्च्यून सरसों तेल अपनी तीव्र सुगंध और प्राकृतिक शुद्धता के लिए जाना जाता है, जो पारंपरिक भारतीय पकवानों के लिए उपयुक्त है।',
                'productPrice' => '210',
                'categoryId' => '11',
                'userId' => '1',
                'stock' => '600',
                'image' => 'productImages/FORTUNEMustardOil.jpeg',
                'season' => 'All',
                'brandId' => '5',
                'isOnHome' => 'yes',
                'status' => 'active',
            ],

            [
                'id' => '8',
                'productName' => 'Amul Buffalo Ghee, 1L',
                'productNameGuj' => 'અમૂલ ભેંસ ઘી',
                'productNameHin' => 'अमूल भैंस घी',
                'productDescription' => 'Amul Buffalo Ghee is crafted from pure buffalo milk, delivering rich taste and superior quality.',
                'productDescriptionGuj' => 'અમૂલ ભેંસ ઘી શુદ્ધ ભેંસના દૂધમાંથી બનેલું છે, જે સમૃદ્ધ સ્વાદ અને શ્રેષ્ઠ ગુણવત્તા પ્રદાન કરે છે.',
                'productDescriptionHin' => 'अमूल भैंस घी शुद्ध भैंस के दूध से बना है, जो समृद्ध स्वाद और उच्च गुणवत्ता प्रदान करता है।',
                'productPrice' => '580',
                'categoryId' => '15',
                'userId' => '1',
                'stock' => '450',
                'image' => 'productImages/AmulBuffaloGhee.jpeg',
                'season' => 'All',
                'brandId' => '4',
                'isOnHome' => 'yes',
                'status' => 'active'
            ],

            [
                'id' => '9',
                'productName' => 'Tata Sampan Chana Dal Fine Besan',
                'productNameGuj' => 'ટાટા સંપન્ન ચણાદાળ ફાઇન બેસન',
                'productNameHin' => ' टाटा संपन्न चना दाल फाइन बेसन',
                'productDescription' => 'Tata Sampan Chana Dal Fine Besan is made from premium quality chana dal, ensuring purity and fine texture for delicious cooking.',
                'productDescriptionGuj' => 'ટાટા સંપન્ન ચણાદાળ ફાઇન બેસન ઉત્તમ ગુણવત્તાની ચણાદાળથી બનાવવામાં આવ્યું છે, જે દરેક વાનગીમાં શુદ્ધતા અને સમૃદ્ધ સ્વાદ સુનિશ્ચિત કરે છે.',
                'productDescriptionHin' => ' टाटा संपन्न चना दाल फाइन बेसन उच्च गुणवत्ता वाली चना दाल से बना है, जो हर व्यंजन में शुद्धता और समृद्ध स्वाद सुनिश्चित करता है।',
                'productPrice' => '59',
                'categoryId' => '1',
                'userId' => '7',
                'stock' => '450',
                'image' => 'productImages/TataSampanChanaDalFineBesan.jpeg',
                'season' => 'All',
                'brandId' => '2',
                'isOnHome' => 'yes',
                'status' => 'active'
            ],

            [
                'id' => '10',
                'productName' => 'ORGANIC INDIA Organic Brown Basmati Rice 1Kg',
                'productNameGuj' => 'ઓર્ગેનિક ઈન્ડિયા ઓર્ગેનિક બ્રાઉન બાસમતી ચોખા 1 કિગ્રા',
                'productNameHin' => 'ऑर्गेनिक इंडिया ऑर्गेनिक ब्राउन बासमती चावल 1 किग्रा',
                'productDescription' => 'Premium quality organic brown basmati rice, rich in fiber and nutrients.',
                'productDescriptionGuj' => 'ઉચ્ચ ગુણવત્તાનું ઓર્ગેનિક બ્રાઉન બાસમતી ચોખા, ફાઇબર અને પોષક તત્વોથી ભરપૂર.',
                'productDescriptionHin' => 'प्रीमियम गुणवत्ता वाला ऑर्गेनिक ब्राउन बासमती चावल, फाइबर और पोषक तत्वों से भरपूर।',
                'productPrice' => '288',
                'categoryId' => '9',
                'userId' => '1',
                'stock' => '600',
                'image' => 'productImages/BrownRiceOrganicIndia.jpeg',
                'season' => 'All',
                'brandId' => '23',
                'isOnHome' => 'yes',
                'status' => 'active'
            ]
        ]);
    }
}
